
STAKE_ON_VALIDATOR = "5G3wMP3g3d775hauwmAZioYFVZYnvw6eY46wkFy8hEWD5KP3" #(Opentensor Foundation by default) Replace with the hotkey of the validator you want to stake with (copy from https://taostats.io/validators )
# Note: The bot can only see and operate alpha staked on the hotkey defined above. Alpha staked on any other validator hotkey are invisible & unusable to the bot.

WALLET_PW = 'your_wallet_password' #Replace with your wallet's password that you entered into btcli
WALLET_NAME = 'bagbot' #The name of the wallet created in btcli

# Note: LOWER THAN 0.01 MAY CAUSE THE BUYS TO FAIL WHILE STILL TAKING THE GAS FEE
MAX_TAO_PER_BUY = 0.02 #May increase as desired, I wouldnt reduce it.
MAX_TAO_PER_SELL = 0.02 #May increase as desired, I wouldnt reduce it
MAX_SLIPPAGE_PERCENT_PER_BUY = 0.2 #If over this slippage %, buy trades won't execute.

# Power curve settings for buy/sell zones (1.0 = linear, >1.0 = more aggressive early, <1.0 = more conservative early)
# Must be positive. Suggested range: 0.1 to 10
BUY_ZONE_POWER = 1.0  # Power curve exponent for buy price progression
SELL_ZONE_POWER = 1.0  # Power curve exponent for sell price progression

# buy_lower is the lowest price that the bot will allocate your max_alpha amount to.  Will only purchase this low if you hold near the max_alpha amount.
# buy_upper is the highest price that the bot will allocate your max_alpha amount to.  Will only purchase this high if you hold no alpha in the subnet yet.
# sell_lower is the lowest price that the bot will sell your alpha.  Will only sell this low if you hold near the max_alpha amount.
# sell_upper is the highest price that the bot will sell your alpha.  Will only sell this high if you hold near almost no alpha in the subnet.
# max_alpha is the maximum amount of alpha to buy in the subnet, the bot will not purchase more.
#
# OPTIONAL PER-SUBNET OVERRIDES (if not specified, uses global defaults above):
# stake_on_validator - Override which validator hotkey to stake on for this subnet (default: STAKE_ON_VALIDATOR)
# max_tao_per_buy - Override max TAO per buy for this subnet (default: MAX_TAO_PER_BUY)
# max_tao_per_sell - Override max TAO per sell for this subnet (default: MAX_TAO_PER_SELL)
# max_slippage_percent_per_buy - Override max slippage % for this subnet (default: MAX_SLIPPAGE_PERCENT_PER_BUY)
# buy_zone_power - Override buy zone power curve for this subnet (default: BUY_ZONE_POWER)
# sell_zone_power - Override sell zone power curve for this subnet (default: SELL_ZONE_POWER)
#
# DELETE THE EXAMPLE SUBNETS BELOW AND ADD SUBNETS AS DESIRED
SUBNET_SETTINGS = {
# Subnet 23 settings:
23: {'buy_lower':  0.000011,
     'buy_upper':  0.000015,
     'sell_lower': 0.5,
     'sell_upper': 1,
     'max_alpha':  10000},
# Subnet 99 settings (with per-subnet overrides example):
99: {'buy_lower':  0.000002,
     'buy_upper':  0.000009,
     'sell_lower': 0.77,
     'sell_upper': 0.99,
     'max_alpha':  100,
     # Example overrides (optional):
     # 'max_tao_per_buy': 0.05,  # Use 0.05 TAO per buy instead of global default
     # 'max_tao_per_sell': 0.03,  # Use 0.03 TAO per sell instead of global default
     # 'max_slippage_percent_per_buy': 0.3,  # Allow 0.3% slippage instead of global default
     # 'stake_on_validator': '5SomeOtherValidatorHotkeyHere',  # Stake on different validator
     # 'buy_zone_power': 2.0,  # More aggressive buying early (stays near buy_upper longer)
     # 'sell_zone_power': 0.5,  # More conservative selling early (drops to sell_lower faster)
     },
}


# COPY EVERYTHING ABOVE THIS LINE TO A NEW FILE NAMED: bagbot_settings_overrides.py IN THIS SAME FOLDER AND ADJUST AS NEEDED. DO NOT EDIT THIS FILE

try:
    from bagbot_settings_overrides import *
except:
    pass

